# Generated by Django 2.2.7 on 2019-12-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='votes_total',
            field=models.IntegerField(default=1),
        ),
    ]
