# Generated by Django 2.2.7 on 2019-12-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191216_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='url',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
